version: "3.8"

services:
  webservice-api:
    container_name: webservice-api
    build:
      context: ./backend/api
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/api:/app
    ports:
      - 9000:9000
    environment:
      - SERVICE_NAME=webservice-api
    env_file:
      - .env.dev

  publish-message-to-consumer-dog:
    container_name: publish-message-to-consumer-dog
    build:
      context: ./backend/api
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/api:/app
    environment:
      - SERVICE_NAME=publish-message-to-consumer-dog
    env_file: .env.dev
    depends_on:
      - queue

  publish-message-to-consumer-cat:
    container_name: publish-message-to-consumer-cat
    build:
      context: ./backend/api
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/api:/app
    environment:
      - SERVICE_NAME=publish-message-to-consumer-cat
    env_file: .env.dev
    depends_on:
      - queue

  queue:
    container_name: queue
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./queue/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./queue/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
  